### ISSUE TITLE
Clean up structure

### ISSUE THREAD

**Issue by griswaldbrooks** [kittcar/kitt_platform#1]

**Comment by kiran-mohan** [comment]
* Removing unnecessary code, correcting names in LICENSE and README.md
* resurrecting .gitignore and .travis.yml, but now with empty content
* renaming victoria_teensy_ros_node to kitt_teensy_ros_node
* renaming victoria_teensy_ros_node.ino to kitt_teensy_ros_node.ino
* correcting project name and github URL

Merged in with this [Pull Request](https://github.com/kittcar/kitt_platform/pull/4)
