### ISSUE TITLE
Have teensy read one ros param

### ISSUE THREAD

**Issue by griswaldbrooks** [kittcar/kitt_platform#21]
Have teensy read a ros param and echo it back.

**Comment by kiran-mohan** [comment]
- [ ] Add a test parameter to the ROS parameter server
- [ ] Read the parameter from the teensy using direct getParam() calls from the Ros::NodeHandle
- [ ] Read the same parameter using the RosParamHelper library

**Comment by griswaldbrooks** [comment]
@kiran-mohan add PR.

**Comment by griswaldbrooks** [comment]
https://github.com/kittcar/kitt_platform/pull/24
