### ISSUE TITLE
Update ros node for kitt

### ISSUE THREAD

**Issue by griswaldbrooks** [kittcar/kitt_platform#3]
Update the teensy node for kitt from victoria.
This might involve removing a lot.

**Comment by griswaldbrooks** [comment]
When doing this, keep in mind possible magellan robot in the future. Not sure what this really means.

**Comment by griswaldbrooks** [comment]
- [ ] Fork victoria_msgs to kitt_msgs, enable issues on repo
- [ ] Install arudino ide, clone ros-serial, clone kitt_platform, clone kitt_msgs
- [ ] Compile existing code with ros-serial and arduino

**Comment by griswaldbrooks** [comment]
Reminded, create branch for this ticket.
Completed when no mention of victoria and builds with travis.
Depends on #5

**Comment by kiran-mohan** [comment]
Changes for this ticket had to be made in both kitt_msgs and kitt_platform.
kitt_platform PR: https://github.com/kittcar/kitt_platform/pull/7
kitt_msgs PR: https://github.com/kittcar/kitt_msgs/pull/1
